### ISSUE TITLE
Gantt chart and Work packages

### ISSUE THREAD

**Issue by Kishaan** [mohanrobotics/Interactive-short-answer-grading#1]
1. Spelling of Gantt chart is wrong! 
2. Work packages should be splitted into main ones and sub-goals.

**Comment by Kishaan** [comment]
The annotations for the milestones are cut halfway in the Gantt chart. I don't think we need some text along the boxes there!

**Comment by mohanrobotics** [comment]
oh yes. I will work on it and will update the changes
